/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.Read4Server;
import Control.Read4ServerMSG;
import Control.Read4ServerThr;
import Control.Send2Server;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author aetox
 */
public class GUIChats extends javax.swing.JFrame {

    private GUILogin guilogin;
    private Send2Server sender;
    private Read4ServerThr reader;
    Read4Server READ;
    private DefaultListModel modelL;
    private String[] parts;
    private String response;
    private StringBuilder sb;
    private String msga;

    /**
     * Creates new form GUIChats
     */
    public GUIChats() {
        initComponents();
    }

    public GUIChats(GUILogin guilogin) {
        this.guilogin = guilogin;
        initComponents();
        this.TableAct();
        this.ChatPanel.setVisible(false);
    }

    private void TableAct() {
        try {
            this.modelL = new DefaultListModel();
            this.response = null;
            String orden = "%logs";
            Read4ServerThr s1 = new Read4ServerThr(this.guilogin.getDB().getServerin(), this.guilogin);
            Thread s2 = new Thread(s1);
            Send2Server f1 = new Send2Server(this.guilogin.getDB().getSocket(), orden, this.guilogin);
            s2.join();
            f1.start();
            response = this.guilogin.getResponse();

            this.StringSep(response);

            for (String s : parts) {
                this.modelL.addElement(s);
            }
            this.OnlineList.setModel(modelL);
        } catch (InterruptedException ex) {
            Logger.getLogger(GUIChats.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void ActP(String msg) {
        this.StringSep(msg);
        this.sb.append(parts[1] + "<br>");
        SimpleAttributeSet left = new SimpleAttributeSet();
        StyleConstants.setAlignment(left, StyleConstants.ALIGN_RIGHT);
        this.TextChat.setParagraphAttributes(left, rootPaneCheckingEnabled);
        this.TextChat.setContentType("text/html");
        this.TextChat.setText(sb.toString());
    }

    private void StringSep(String line) {
        this.parts = line.split("-");
    }

    public JTextPane getTextChat() {
        return TextChat;
    }

    public void setMsga(String msga) {
        this.msga = msga;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuSesion = new javax.swing.JPopupMenu();
        Salir1 = new javax.swing.JMenuItem();
        CerrarSesion1 = new javax.swing.JMenuItem();
        Iniciar = new javax.swing.JInternalFrame();
        IniciarB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ChatNow = new javax.swing.JPanel();
        LateralPanel = new javax.swing.JPanel();
        IconHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OnlineList = new javax.swing.JList<>();
        SesionButon = new javax.swing.JLabel();
        ChatPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        NameChat = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextChat = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        msgchat = new javax.swing.JTextField();
        send = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Bk = new javax.swing.JLabel();

        Salir1.setText("Salir");
        Salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir1ActionPerformed(evt);
            }
        });
        MenuSesion.add(Salir1);

        CerrarSesion1.setText("Cerrar sesion");
        CerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesion1ActionPerformed(evt);
            }
        });
        MenuSesion.add(CerrarSesion1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Iniciar.setBackground(new java.awt.Color(0, 0, 0));
        Iniciar.setBorder(null);
        Iniciar.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Iniciar.setVisible(true);
        Iniciar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IniciarB.setBackground(new java.awt.Color(204, 0, 0));
        IniciarB.setFont(new java.awt.Font("Nimbus Roman No9 L", 1, 36)); // NOI18N
        IniciarB.setForeground(new java.awt.Color(255, 255, 255));
        IniciarB.setText("INICIAR");
        IniciarB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        IniciarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarBActionPerformed(evt);
            }
        });
        Iniciar.getContentPane().add(IniciarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 410, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelaneos/1280x720-black-solid-color-background.png"))); // NOI18N
        Iniciar.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1280, 720));

        getContentPane().add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        ChatNow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LateralPanel.setBackground(new java.awt.Color(0, 0, 0));
        LateralPanel.setAutoscrolls(true);
        LateralPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelaneos/LogoBlanco1.png"))); // NOI18N
        IconHeader.setText("jLabel2");
        IconHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconHeaderMouseClicked(evt);
            }
        });
        LateralPanel.add(IconHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 6, 239, 84));

        OnlineList.setBackground(new java.awt.Color(39, 39, 39));
        OnlineList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        OnlineList.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        OnlineList.setForeground(new java.awt.Color(255, 255, 255));
        OnlineList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        OnlineList.setValueIsAdjusting(true);
        OnlineList.setVisibleRowCount(10);
        OnlineList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                OnlineListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(OnlineList);

        LateralPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 350, 624));

        SesionButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelaneos/outline_list_white_24dp.png"))); // NOI18N
        SesionButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SesionButonMouseClicked(evt);
            }
        });
        LateralPanel.add(SesionButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 50));

        ChatNow.add(LateralPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 720));

        ChatPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(39, 39, 39));

        NameChat.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        NameChat.setForeground(new java.awt.Color(255, 255, 255));
        NameChat.setText("Persona");
        jPanel1.add(NameChat);

        ChatPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 580, 60));

        TextChat.setBackground(new java.awt.Color(39, 39, 39));
        TextChat.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(TextChat);

        ChatPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 670, 480));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msgchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgchatActionPerformed(evt);
            }
        });
        jPanel2.add(msgchat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 640, 30));

        send.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelaneos/outline_send_white_24dp.png"))); // NOI18N
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });
        jPanel2.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 60, 30));

        ChatPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 870, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelaneos/Chat.jpg"))); // NOI18N
        ChatPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 670));

        ChatNow.add(ChatPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 930, 670));

        Bk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelaneos/945893.png"))); // NOI18N
        ChatNow.add(Bk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(ChatNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarBActionPerformed
        Read4ServerMSG msgreader = new Read4ServerMSG(this.guilogin.getDB().getServerin(), this);
        msgreader.start();
        Read4Server READ = new Read4Server(this.guilogin.getDB().getServerin(), this);
        READ.execute();
        this.TableAct();
        this.Iniciar.setVisible(false);
        DefaultListCellRenderer renderer = (DefaultListCellRenderer) this.OnlineList.getCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        renderer.setBackground(Color.red);
        this.guilogin.setResponse("");
    }//GEN-LAST:event_IniciarBActionPerformed

    private void OnlineListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_OnlineListValueChanged

        String selected = null;
        selected = this.OnlineList.getSelectedValue().toString();
        this.ChatPanel.setVisible(true);
        this.NameChat.setText(selected);
        String orden = "%act-" + this.guilogin.getLogin() + "-" + selected;
        Send2Server f2 = new Send2Server(this.guilogin.getDB().getSocket(), orden, this.guilogin);
        f2.start();

        SimpleAttributeSet right = new SimpleAttributeSet();
        StyleConstants.setAlignment(right, StyleConstants.ALIGN_RIGHT);
        this.sb = new StringBuilder();

        this.StringSep(this.guilogin.getResponse());
        for (int j = 0; j < this.parts.length; j++) {
            sb.append(this.parts[j] + "<br>");
        }
        this.TextChat.setForeground(Color.black);
        this.TextChat.setContentType("text/html");
        this.TextChat.setParagraphAttributes(right, rootPaneCheckingEnabled);
        this.TextChat.setText(sb.toString());
    }//GEN-LAST:event_OnlineListValueChanged

    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
        String msg = this.guilogin.getLogin() + " : " + this.msgchat.getText();
        this.msgchat.setText("");
        String orden1 = "%insert" + "-INSERT INTO `tbl_chats` (`ID_Chat`, `Correo_Contacto`, `Sender`, `Mensaje`) VALUES (NULL," + "'" + this.OnlineList.getSelectedValue().toString() + "'" + "," + "'" + this.guilogin.getLogin() + "'" + "," + "'" + msg + "');";
        SimpleAttributeSet right = new SimpleAttributeSet();
        StyleConstants.setAlignment(right, StyleConstants.ALIGN_RIGHT);
        this.TextChat.setParagraphAttributes(right, rootPaneCheckingEnabled);
        sb.append(msg + " <br>");

        this.TextChat.setParagraphAttributes(right, rootPaneCheckingEnabled);
        this.TextChat.setForeground(Color.black);
        this.TextChat.setContentType("text/html");
        this.TextChat.setText(sb.toString());
        Send2Server f3 = new Send2Server(this.guilogin.getDB().getSocket(), orden1, this.guilogin);
        f3.start();
        String orden2 = "%msg-" + msg + "-" + this.OnlineList.getSelectedValue();
        Send2Server f4 = new Send2Server(this.guilogin.getDB().getSocket(), orden2, this.guilogin);
        f4.start();
        this.guilogin.setResponse("");
    }//GEN-LAST:event_sendMouseClicked

    private void IconHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconHeaderMouseClicked
        this.TableAct();
    }//GEN-LAST:event_IconHeaderMouseClicked

    private void SesionButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SesionButonMouseClicked
        this.MenuSesion.show(this.SesionButon, this.SesionButon.getWidth() / 2, this.SesionButon.getHeight() / 2);
    }//GEN-LAST:event_SesionButonMouseClicked

    private void Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir1ActionPerformed
        Send2Server f5 = new Send2Server(this.guilogin.getDB().getSocket(), "%quit", this.guilogin);
        f5.start();
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_Salir1ActionPerformed

    private void CerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesion1ActionPerformed
        Send2Server f6 = new Send2Server(this.guilogin.getDB().getSocket(), "%quit", this.guilogin);
        f6.start();
        GUILogin guilog = new GUILogin();
        this.setVisible(false);
        this.guilogin.setVisible(true);
    }//GEN-LAST:event_CerrarSesion1ActionPerformed

    private void msgchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgchatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msgchatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIChats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIChats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIChats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIChats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIChats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bk;
    private javax.swing.JMenuItem CerrarSesion1;
    private javax.swing.JPanel ChatNow;
    private javax.swing.JPanel ChatPanel;
    private javax.swing.JLabel IconHeader;
    private javax.swing.JInternalFrame Iniciar;
    private javax.swing.JButton IniciarB;
    private javax.swing.JPanel LateralPanel;
    private javax.swing.JPopupMenu MenuSesion;
    private javax.swing.JLabel NameChat;
    private javax.swing.JList<String> OnlineList;
    private javax.swing.JMenuItem Salir1;
    private javax.swing.JLabel SesionButon;
    private javax.swing.JTextPane TextChat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField msgchat;
    private javax.swing.JLabel send;
    // End of variables declaration//GEN-END:variables
}
