/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.Cliente;
import Control.Read4Server;
import Control.Read4ServerThr;
import Control.Send2Server;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author aetox
 */
public class GUILogin extends javax.swing.JFrame {

    /**
     * Creates new form GUILogin
     */
    private Cliente DB;
    private Send2Server S;
    private Read4Server r;
    private Read4ServerThr s1;
    private GUIChats guichats;
    String response;
    private String user;
    private String pass;
    private String login;

    public GUILogin() {
        initComponents();
        DB = new Cliente("localhost", 5555);
        DB.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        HeaderWelcome = new javax.swing.JLabel();
        HeaderLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EmailText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        IngresarB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BRegister = new javax.swing.JLabel();
        TextPass = new javax.swing.JPasswordField();
        Icon = new javax.swing.JLabel();
        BackGImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Benzaiten");
        setName("Benzaiten"); // NOI18N
        setResizable(false);

        BackGroundPanel.setBackground(new java.awt.Color(55, 6, 23));
        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(39, 39, 39));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        HeaderWelcome.setFont(new java.awt.Font("URW Gothic L", 1, 14)); // NOI18N
        HeaderWelcome.setForeground(new java.awt.Color(112, 112, 112));
        HeaderWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderWelcome.setText("BIENVENIDO DE NUEVO");
        HeaderWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        HeaderLogin.setFont(new java.awt.Font("Fira Sans", 0, 32)); // NOI18N
        HeaderLogin.setForeground(new java.awt.Color(255, 255, 255));
        HeaderLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderLogin.setText("Ingresa a tu cuenta");

        jLabel1.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email:");

        EmailText.setBackground(new java.awt.Color(39, 39, 39));
        EmailText.setForeground(new java.awt.Color(255, 255, 255));
        EmailText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmailText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 112, 112), 1, true));

        jLabel2.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");

        IngresarB.setBackground(new java.awt.Color(14, 67, 250));
        IngresarB.setForeground(new java.awt.Color(255, 255, 255));
        IngresarB.setText("Ingresar ahora");
        IngresarB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 39, 39)));
        IngresarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IngresarB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresarBMouseClicked(evt);
            }
        });
        IngresarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarBActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(112, 112, 112));
        jLabel3.setText("No esta registrado aun? ");

        BRegister.setForeground(new java.awt.Color(255, 255, 255));
        BRegister.setText("Registrarse");
        BRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BRegisterMouseClicked(evt);
            }
        });

        TextPass.setBackground(new java.awt.Color(39, 39, 39));
        TextPass.setForeground(new java.awt.Color(255, 255, 255));
        TextPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(HeaderLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BRegister))
                            .addComponent(EmailText)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngresarB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextPass, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(HeaderWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(HeaderWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HeaderLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextPass, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(IngresarB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BRegister))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        BackGroundPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 132, -1, -1));

        Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelaneos/LogoBlanco1.png"))); // NOI18N
        BackGroundPanel.add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 230, 80));

        BackGImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelaneos/5805468.png"))); // NOI18N
        BackGImg.setToolTipText("");
        BackGImg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BackGImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BackGImg.setPreferredSize(new java.awt.Dimension(1280, 720));
        BackGImg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BackGroundPanel.add(BackGImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 1300, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarBActionPerformed
        this.user = this.EmailText.getText();
        this.pass = this.TextPass.getText();
        if (user.isEmpty() || pass.isEmpty()) {
            this.HeaderWelcome.setForeground(Color.red);
            this.HeaderWelcome.setText("Los espacios no pueden estar en blanco >:|");
        } else {
            String sentencia = "%session" + "-SELECT tbl_Registro.Contra_Usuario_Registro,tbl_Registro.Nombre FROM tbl_Registro WHERE tbl_Registro.Correo_Usu = " + "'" + user + "'" + "-" + pass;

            S = new Send2Server(DB.getSocket(), sentencia, this);
            S.start();
            s1 = new Read4ServerThr(DB.getServerin(), this);
            s1.start();

        }
    }//GEN-LAST:event_IngresarBActionPerformed

    public void ThreadIn() {
        s1 = new Read4ServerThr(DB.getServerin(), this);
    }

    public String getResponse() {
        return response;
    }

    public void setResponse(String response) {
        this.response = response;
    }

    public Cliente getDB() {
        return DB;
    }

    public String getUser() {
        return user;
    }

    public String getPass() {
        return pass;
    }

    public String getLogin() {
        return login;
    }

    public JLabel getHeaderWelcome() {
        return HeaderWelcome;
    }

    public Read4Server getR() {
        return r;
    }

    public GUIChats getGuichats() {
        return guichats;
    }

    private void BRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BRegisterMouseClicked
        GUIRegistro guiRegistro = new GUIRegistro(this);
        this.setVisible(false);
        guiRegistro.setVisible(true);

    }//GEN-LAST:event_BRegisterMouseClicked

    public Read4ServerThr getS1() {
        return s1;
    }

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void IngresarBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarBMouseClicked
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            //siguiente frame;

            if (this.response.contains("1")) {
                String[] parts = this.response.split("-");
                this.login = parts[1];
                this.setVisible(false);
                this.guichats = new GUIChats(this);
                guichats.setVisible(true);
            } else {
                this.HeaderWelcome.setForeground(Color.red);
                this.HeaderWelcome.setText("La contraseña o el correo estan incorrectos :(");
            }

        }
    }//GEN-LAST:event_IngresarBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BRegister;
    private javax.swing.JLabel BackGImg;
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JTextField EmailText;
    private javax.swing.JLabel HeaderLogin;
    private javax.swing.JLabel HeaderWelcome;
    private javax.swing.JLabel Icon;
    private javax.swing.JButton IngresarB;
    private javax.swing.JPasswordField TextPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
